Point the test suite at the Python bindings directory.
At the moment it's required during the build. Otherwise, the test suite
errors out with:

    ModuleNotFoundError: No module named 'pirogue_admin_api'

This is an alternative to having the package listed in Build-Depends,
which means developers don't have to install packages… and keep them in
sync!