Add pirogue-admin-api to Build-Depends.
At the moment it's required during the build. Otherwise, the test suite
errors out with:

    ModuleNotFoundError: No module named 'pirogue_admin_api'